### ISSUE TITLE
Feature: User can upload a picture of their clothing item.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can upload a picture, or take a picture of their clothing item

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can either choose a file from their device and is also given the option to take a photo on their mobile device camera.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="856" alt="Screen Shot 2021-11-02 at 1 04 08 PM" src="https://user-images.githubusercontent.com/87718271/139944131-c142e4a4-b0cc-4bd9-858d-faed30a84499.png">

<img width="754" alt="Screen Shot 2021-11-02 at 1 04 39 PM" src="https://user-images.githubusercontent.com/87718271/139944174-6a97469c-7695-4e9f-8eef-d49df819f95e.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to sql script exported from db designer.
- [x] Update `data.sql` to have one user with userId: 1, article types: "top, bottom, and shoes", colorCategories: "black, white, grey, red, yellow, green, blue, magenta, and khaki"

### ☁️ Server

- [x] Update `server/index.js` to handle post requests 
- [x] Parse the request body with JSON middleware
- [x] When their is a POST request with path 'api/articles/1' - path will be 'api/inventory/userId' after login is built
- [x] Check that the post has all required info in the body including: url, article type id, primary color, color category id
  - [x] Insert the new article into the database with SQL  
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a navbar component
- [x] Create a component to accept inputs including a img file, article type from a dropdown and upload button to submit 
- [x] Create an encapsulating page component containing the above components
- [x] Update component to display the image file's url in the input text and display the image
  - [x] Update component after image has loaded to display the color squares 
- [x] Update component to display the url and image that a user takes with their camera
- [x] Update component to handle submit and send a fetch request to post new article to database
- [x] Update component to reset after submitting an article of clothing
- [x] Resize image files that are too large, to allow upload to database.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

Research Links 
- Color Thief, for extracting dominant colors of an image https://lokeshdhakar.com/projects/color-thief/#api 
- Bootstrap, https://getbootstrap.com/docs/3.3/getting-started/
- Color Convert, for converting RGB colors to HSL for categorizing
