### ISSUE TITLE
Feature: User can view their saved outfits 

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can view their saved outfits 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their collection of saved outfits in an 'Outfits' page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="266" alt="Screen Shot 2021-11-12 at 10 48 11 AM" src="https://user-images.githubusercontent.com/87718271/141519263-0de3e1e4-3184-43e8-a355-4064a7d280cb.png">
<img width="730" alt="Screen Shot 2021-11-12 at 10 49 20 AM" src="https://user-images.githubusercontent.com/87718271/141519411-03aec631-9295-4963-ab79-700ee0930b8a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to get requests at path '/api/outfits/1'
  - [x] Server queries database for all outfits and corresponding articles
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to hold an outfit
- [x] Create a outfits page component to hold outfit components
- [x] On componentDidMount send fetch get request to server
- [x] Add outfits option to app drawer

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
