### ISSUE TITLE
Feature: User can set the item's primary and secondary color categories

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set the item's primary and secondary color groups. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be displayed with auto generated primary and secondary colors but will be able to override these values if they are not accurate.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="792" alt="Screen Shot 2021-11-02 at 11 42 19 AM" src="https://user-images.githubusercontent.com/87718271/139925552-625473b7-b850-479b-ac22-97d7f48da7c9.png">
<img width="652" alt="Screen Shot 2021-11-02 at 11 42 36 AM" src="https://user-images.githubusercontent.com/87718271/139925601-7853bc9b-f708-470a-b183-ea1d9c436816.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add select elements to React form component
  - [x] Mobile view, add one select element that switches selection for primary and secondary color categories
  - [x] Add a color select property to the state of the form element
  - [x] Add an event listener to the primary and secondary color squares that listens for click events and
    - [x] Updates color select property of state to either primary or secondary
  - [x] Create a handle change function for the select element that sets primary or secondary color's category and id's, depending on the state
  - [x] In desktop view have two select elements, one for primary and one for secondary color category selection
  - [x] Get matching colorCategoryId for selected color and update state
- [x] Update component to display auto extracted color categories in the select value, first
- [x] Update component to display new selected color in the color squares 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
