### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can enter their username and password to sign up

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-13 at 1 32 13 PM](https://user-images.githubusercontent.com/87718271/141659627-84e9823c-b3aa-4404-aab5-685ea5154352.png)

![Screen Shot 2021-11-13 at 1 32 31 PM](https://user-images.githubusercontent.com/87718271/141659621-dc1e7a45-19bf-44da-89ad-9eb2a623aca2.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to post requests at path '/api/auth/sign-up'
  - [x] Server checks if there is a username and a password
  - [x] Hashes the password and stores the hashed password in the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to hold an authorization form
- [x] Create a sign-up page component
- [x] Update component to handle changes on the input elements and update state to the values
- [x] onSubmit of the form send a fetch post request to server
  - [x] Reset form  

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
