### ISSUE TITLE
Feature: User can login

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#22]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can access the app when they provide their credentials 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to post requests at '/api/auth/sign-in'
  - [x] Checks if there is a user under userId
  - [x] Server checks if there is a username and password then queries the database to compare user entered password hashed and hashedPassword assigned to according username
  - [x] If the passwords match, respond with user's payload with signed token
- [x] Update server route paths to respond to userId from req.user (rather than hardcoded userId=1"
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update auth-form component to handle both sign up and sign in 
- [x] Add a button to switch between sign up and sign in
- [x] Update fetch request to send request for either sign-up or sign-in 
- [x] Create redirect component to redirect to sign in page if there is no user
- [x] Add context to app.jsx
- [x] Update AuthPage component to use app context
- [x] Update components to get userId from context to send fetch request to specified id
- [x] Add sign out button to app drawer 
- [x] Update app.jsx to handle sign in and sign out

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
