### ISSUE TITLE
Feature: User can view their inventory of clothing items.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their inventory of clothing items.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to select a "Inventory" tab from an app drawer, where they will be able to view all articles of clothing they uploaded.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="546" alt="Screen Shot 2021-11-02 at 11 45 10 AM" src="https://user-images.githubusercontent.com/87718271/139925929-bcfa8c68-0659-4f28-85e2-0af7beb73327.png">

<img width="783" alt="Screen Shot 2021-11-02 at 11 45 33 AM" src="https://user-images.githubusercontent.com/87718271/139925962-2286e2f4-605c-49a3-82b1-c1c82fbbf317.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to get requests
  - [x] Retrieve all articles of clothing from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a clothing article component 
- [x] Create an inventory page component made up of clothing article components 
  - [x] On componentDidMount, send fetch GET request to server for articles
  - [x] Update state property articles array to the data response
  - [x] Map through articles array and render clothing article components
- [x] Create an app drawer component
- [x] Update Navbar component to have a menu icon
  - [x] Listen for clicks on the menu icon
    - [x] Update Navbar state to reflect if app drawer is open, toggle state
- [x] Add route to App component state
- [x] Add hash routing functionality
- [x] Listen for clicks on the app drawer 
  - [x] Switch to inventory page view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
