### ISSUE TITLE
Feature: User can view their items filtered by clothing article type.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can view their items sorted by clothing item type.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to sort their inventory to view only a certain clothing item type such as their "Tops" or "Bottoms"

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="567" alt="Screen Shot 2021-11-02 at 11 47 02 AM" src="https://user-images.githubusercontent.com/87718271/139926448-943d1c95-7e0c-4ec7-9e95-b18f5c8191e8.png">

<img width="759" alt="Screen Shot 2021-11-02 at 11 47 22 AM" src="https://user-images.githubusercontent.com/87718271/139926480-970b884e-c1c4-4645-8ed9-bec2ec228129.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to get requests at path '/api/inventory/1/:articleType'
  - [x] Query database to get all articles of clothing that matches the article type
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update inventory page component to have a dropdown select for article type
- [x] Listen for changes on the dropdown input and 
  - [x] Send a fetch request to the server for the selected type of article 
  - [x] Update articles property of state to the response data 
- [x] Update inventory component to display corresponding article type placeholder image

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
