### ISSUE TITLE
Feature: User can delete clothing items from their inventory.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete clothing items from their inventory.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to remove unwanted clothing items from their inventory. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="244" alt="Screen Shot 2021-11-02 at 11 48 58 AM" src="https://user-images.githubusercontent.com/87718271/139926688-b533c3db-f68a-48a1-a28d-f8cef6120297.png">

<img width="758" alt="Screen Shot 2021-11-02 at 11 49 15 AM" src="https://user-images.githubusercontent.com/87718271/139926725-0afec62b-7ef4-45f4-9209-593f7a46d61d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to delete requests at '/api/inventory/1/:articleId'
  - [x] Server deletes article from the database at specified articleId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update article component to render each article with a delete button
- [x] Update article component to have a dataKey attribute with a value of its articleId
- [x] Listen for clicks onClick events on the delete button 
  - [x] Send a fetch delete request to server with the article's dataKey attribute 
  - [x] Get the articles index in the articles array
  - [x] Copy the articles array from state
  - [x] Delete the article at the selected article's index from this copied array
  - [x] Assign state property articles to the new array 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
