### ISSUE TITLE
Feature: User can view tops matching the selected color.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view tops matching the selected color

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view all tops from their inventory that have a primary or secondary color that matches the selected color.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="818" alt="Screen Shot 2021-11-02 at 11 53 53 AM" src="https://user-images.githubusercontent.com/87718271/139927344-08a97a72-c28a-4c89-a6db-8001eab3233c.png">

<img width="906" alt="Screen Shot 2021-11-02 at 11 54 16 AM" src="https://user-images.githubusercontent.com/87718271/139927397-4c23d824-9cf4-4e00-ae93-6de427354402.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to  respond to get requests for tops of a specific color '/api/inventory/1/:articleType/:color'
  - [x] Assign colorId from its matching color 
  - [x] Server queries database for all articles matching the colorId 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to hold all the tops of a specific color, carousel
- [x] Create an outfit picker page component
- [x] Add outfit picker option to app drawer
- [x] Add an select element to choose a color 
- [x] Listen for onChange events on the select element and
  - [x] Send a fetch a get request for the tops of the selected color
  - [x] Update component state, topOptions to the new array of articles from the fetched data

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
