### ISSUE TITLE
Feature: User can view an outfit choice.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view an outfit choice.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view an outfit choice, which includes a top, bottom, and shoes and the user can choose a color for each article of clothing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="697" alt="Screen Shot 2021-11-02 at 11 55 56 AM" src="https://user-images.githubusercontent.com/87718271/139927682-3c5be599-1f6c-41ce-81ee-2008f39743d9.png">

<img width="736" alt="Screen Shot 2021-11-02 at 11 56 41 AM" src="https://user-images.githubusercontent.com/87718271/139927737-0c05b63a-3c66-4aee-a99d-bb3eff2b63ab.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond with matching article type placeholder image if query returns empty
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add articleOptions carousel components to picker page component
- [x] Add a prop for the type of article to articleOptions component
- [x] Edit articleOptions component to send a fetch get request for its article type and selected color

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
