### ISSUE TITLE
Feature: User can save an outfit.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save an outfit to their “Outfits”.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to save an outfit from the "Outfit Picker" to their "Outfits".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="516" alt="Screen Shot 2021-11-02 at 11 58 39 AM" src="https://user-images.githubusercontent.com/87718271/139927949-408a62a1-36e4-42d8-b196-dd8d7976a4e2.png">
<img width="841" alt="Screen Shot 2021-11-02 at 11 58 59 AM" src="https://user-images.githubusercontent.com/87718271/139927999-6d4f1397-daa5-4e34-9793-8aa58c5bde1d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to a fetch post request for an outfit at 'api/outfits/1/' 
- [x] Server queries that database and inserts a new outfit into outfits table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a button to the picker page that sends a fetch post request to the server
- [x] Update picker-page component to have state properties for each articleId
- [x] On mouseLeave on the carousel, pass the currentArticle to props onMouseLeave
- [x] In picker page, onMouseLeave prop passed to carousel, setState to the caught current article
- [x] Listen for onclicks on the add to outfits button and
  - [x] send fetch post request to server 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
