### ISSUE TITLE
Feature: User can add an accompanying picture of themselves wearing the outfit.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an accompanying picture of themselves wearing the outfit .

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to upload or take a photo of themselves wearing the outfit in their "Outfits".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="471" alt="Screen Shot 2021-11-02 at 12 00 53 PM" src="https://user-images.githubusercontent.com/87718271/139928248-63518600-c3f4-4db6-b979-92fc2ed2a771.png">

<img width="911" alt="Screen Shot 2021-11-02 at 12 01 21 PM" src="https://user-images.githubusercontent.com/87718271/139928296-32ddad07-9d70-4616-807f-13fa582fe135.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include a selfieImgUrl column to outfits table
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
